### PR TITLE
W426: Debug PDF Annotation Navigation

### LINKED ISSUE #426: Navigation to PDF Annotation is Broken

### PR DESCRIPTION
**Pull request by JonasMS**
close #426

### CODE REVIEW

File: src/common/components/AnnotationContainer/index.js [hunk 1]
```diff
@@ -240,35 +240,34 @@ class AnnotationContainer extends Component {
             return;
         }
 
-        const {annotation} = this.props,
-            {target, page, id} = annotation,
-            {source} = target,
-            urlParams = new URLSearchParams(source);
+        const {page, id, url} = this.props.annotation,
+            // {url} = target,
```
Comment (JonasMS) [inline src/common/components/AnnotationContainer/index.js]: remove commented-out code
