### PR TITLE
W341: Debug Autosuggest, Body Input UX

### LINKED ISSUE #341: `Tag Options Suggestions` is broken

### PR DESCRIPTION
**Pull request by JonasMS**
close #341

### CODE REVIEW

File: src/common/components/Annotation/index.js [hunk 1]
```diff
@@ -51,11 +50,11 @@ export default class Annotation extends Component {
                 <div className={classnames('annotation-data-container body-data-container', {show: !disableBody})}>
                     <TextEditor
                         editorState={editorState}
+                        handleKeyCommand={onKeyCommand} // TODO change to handleKeyCommand to mirror draf-js Editor
```
Comment (JonasMS) [inline src/common/components/Annotation/index.js]: remove comment, TODO completed

File: src/libs/extensionApp/sidePanel/src/components/AnnotationPanel/style.scss [hunk 2]
```diff
@@ -9,6 +9,11 @@
         margin-left: 15px;
     }
 
+    // TODO refac draft-js Editor component styling
+    .body-container {
```
Comment (JonasMS) [inline src/libs/extensionApp/sidePanel/src/components/AnnotationPanel/style.scss]: remove, no longer using

File: src/common/components/TextEditor/style.scss [hunk 3]
```diff
@@ -1,42 +1,32 @@
 .body-container {
     border-left: 2px solid #F2C94C;
-    line-height: 22px;
-    font-size: 16px;
-    letter-spacing: 0.2px;
 
-    .DraftEditor-root {
+    .DraftEditor-editorContainer {
+        border: 1px solid #FEFEFE;
```
[the remark this answers is not in the document]
Comment (JonasMS) [reply src/common/components/TextEditor/style.scss]: 👍

File: src/libs/extensionApp/sidePanel/src/components/AnnotationPanel/style.scss (hunk 2 above)
Comment (JonasMS) [reply src/libs/extensionApp/sidePanel/src/components/AnnotationPanel/style.scss]: 👍
