### PR TITLE
W480: fix browserUtils.getURL on PDFs that don't contain '.pdf'

### LINKED ISSUE #480: PDFs that don't end w/ '.pdf' break browserUtils.getDocumentURL
* want to get the entire pdf url without and query params ('?' or '#')
* why do we need the PDF url if fingerprint is all that matters for PDFs?
* checking for '.pdf' is an invalid test

example of PDF w/ out '.pdf': https://www.scp.nl/dsresource?objectid=93747669-7ecb-48e6-acd7-17fda1164c3d&type=org

### PR DESCRIPTION
**Pull request by JonasMS**
close #480

### CODE REVIEW

File: src/common/util/browserUtils.js [hunk 1]
```diff
@@ -29,11 +29,16 @@ const
...
     getDocumentURL = (isPDF = window.location.href.indexOf('.pdf') > 0) => {
-        const { href } = window.location;
+        if (isPDF) {
+            const pdfURL = window.location.href.match(/chrome-extension:\/\/.*\/([^\?].*:\/\/.*)/)[1],
+                parsedURL = new URL(pdfURL);
 
-        return isPDF
-            ? href.match(/chrome-extension:\/\/.*\/([^\?].*:\/\/.*.pdf)/)[1]
-            : href;
+            parsedURL.hash = '';
```
Comment (JonasMS) [inline src/common/util/browserUtils.js]: don't erase hash

File: src/server/routes/api.js [hunk 2]
```diff
@@ -69,10 +69,8 @@ router.post('/api/create', upload.single('upl'), (req, res) => {
                 url: documentURL,
             })
             : annotation.document,
-        {url, fingerprint, isPDF} = annotation.document,
-        whereQuery = (isPDF && url && url.toLowerCase().includes('.pdf')) ?
-            {fingerprint} :
-            {url};
+        {url, fingerprint } = annotation.document,
```
Comment (JonasMS) [inline src/server/routes/api.js]: fix spacing

File: src/common/util/browserUtils.js (hunk 1 above)
Comment (JonasMS) [reply src/common/util/browserUtils.js]: 👍

File: src/server/routes/api.js (hunk 2 above)
Comment (JonasMS) [reply src/server/routes/api.js]: 👍
