### PR TITLE
W322: Refac Panel Error Messaging

### LINKED ISSUE #322: Error Messaging: Broken Web PDF
1) update 'save PDF' error message to suggest downloading + opening PDF w/ chrome

2) show error message on 'annotation create' failures

### PR DESCRIPTION
**Pull request by JonasMS**
close #322 
* consolidate 'status panel' and 'side panel'
* provide more helpful error messaging when PDF save fails

### CODE REVIEW

File: src/libs/extensionApp/common/constants.js [hunk 1]
```diff
@@ -13,5 +13,12 @@ export const
     PASS_ANNOTATIONS_LIST = 'PASS_ANNOTATIONS_LIST',
     SHOW_SIDE_PANEL = 'SHOW_SIDE_PANEL',
     SHOW_SIDE_PANEL_ANNOTATION = 'SHOW_SIDE_PANEL_ANNOTATION',
+    // TODO remove status panel things
```
Comment (JonasMS) [inline src/libs/extensionApp/common/constants.js]: complete TODO

File: src/libs/extensionApp/sidePanel/src/components/PanelContainer.js [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+    SUCCESS_PANEL,
+    WORKING_PANEL,
+} from '../../../common/constants';
+import {ERROR_CODE_E1100} from '../../../../../common/errorCodes';
+
+const brokenPDFLink = 'https://intercom.help/athena-cbb104a68809/faq/pdf-documents-with-athena/cant-save-a-pdf-to-my-athena-account-or-cant-create-annotations-on-a-pdf';
+
+// TODO rename 'PanelManager'?
+const PanelContainer = (props) => {
+    // const {tags} = props;
```
Comment (JonasMS) [inline src/libs/extensionApp/sidePanel/src/components/PanelContainer.js]: remove

File: src/libs/extensionApp/sidePanel/src/components/PanelContainer.js [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+    ANNOTATION_PANEL,
+    ERROR_PANEL,
+    SUCCESS_PANEL,
+    WORKING_PANEL,
+} from '../../../common/constants';
+import {ERROR_CODE_E1100} from '../../../../../common/errorCodes';
+
+const brokenPDFLink = 'https://intercom.help/athena-cbb104a68809/faq/pdf-documents-with-athena/cant-save-a-pdf-to-my-athena-account-or-cant-create-annotations-on-a-pdf';
+
+// TODO rename 'PanelManager'?
```
Comment (JonasMS) [inline src/libs/extensionApp/sidePanel/src/components/PanelContainer.js]: consider TODO

File: src/libs/extensionApp/sidePanel/src/index.js [hunk 4]
```diff
@@ -1,25 +1,32 @@
 import React, { Component } from 'react';
-import AnnotationPanel from './components/AnnotationPanel';
-import AuthenticationPanel from './components/AuthenticationPanel';
+import PanelContainer from './components/PanelContainer';
+// import AnnotationPanel from './components/AnnotationPanel';
```
Comment (JonasMS) [inline src/libs/extensionApp/sidePanel/src/index.js]: remove

File: src/libs/extensionApp/sidePanel/src/index.js [hunk 5]
```diff
@@ -294,12 +303,14 @@ export default class SidePanel extends Component {
         this.setState({ annotations });
     }
 
-    handleSidePanelHide() {
-        postMessage(this.controllerWindow, this.controllerOrigin, HIDE_SIDE_PANEL);
-        this.setState({
-            displayMainCard: false,
-            displayPopupCard: false,
-        });
+    // TODO rename to `panelHide`
```
Comment (JonasMS) [inline src/libs/extensionApp/sidePanel/src/index.js]: TODO completed, remove

File: src/libs/extensionApp/common/constants.js (hunk 1 above)
Comment (JonasMS) [reply src/libs/extensionApp/common/constants.js]: 👍

File: src/libs/extensionApp/sidePanel/src/components/PanelContainer.js (hunk 2 above)
Comment (JonasMS) [reply src/libs/extensionApp/sidePanel/src/components/PanelContainer.js]: 👍

File: src/libs/extensionApp/sidePanel/src/components/PanelContainer.js (hunk 3 above)
Comment (JonasMS) [reply src/libs/extensionApp/sidePanel/src/components/PanelContainer.js]: 👍

File: src/libs/extensionApp/sidePanel/src/index.js (hunk 4 above)
Comment (JonasMS) [reply src/libs/extensionApp/sidePanel/src/index.js]: 👍

File: src/libs/extensionApp/sidePanel/src/index.js (hunk 5 above)
Comment (JonasMS) [reply src/libs/extensionApp/sidePanel/src/index.js]: 👍
