### PR TITLE
W294: Debug Controller Bugs

### LINKED ISSUE #294: Controller Bugs
[x] 1)
bug: paragraph select (triple-click) loses part of the selection (paragraph) `<em>` tag

url: http://blog.coleadership.com/how-to-invest-in-the-infrastructure-of-your-relationships/ 

string:"The impact of investing in this infrastructure has been readily observable: many hard things become easy."

[x] 2)
bug: normal select (dragging mouse) on table loses part of select if mouse is not over the final node on 'mouse up'

url: https://catalog.data.gov/dataset/demographic-statistics-by-zip-code-acfc9

[ ] 3)
bug: second annotation in a node does not get located. Annotation Engine skips node once it finds an annotation in the node.

[x] 4)
bug: selection is only partially undone when making a non-selecting click on a non-controller node

url: https://medium.com/dating-meets-data/questions-to-spark-authenticity-bac0099f04a7

string: "
... Here’s an excerpt from the article, followed by the questions!

Is there a shortcut to bonding with a romantic partner on a deeper level?
"

[x] 5)
bug: Modifications to Selection using the keyboard are not wrapped by Controller Nodes

[can't reproduce] 6)
bug: comment text selected on Reddit.com gets modified

### PR DESCRIPTION
**Pull request by JonasMS**
close #294

### CODE REVIEW

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js [hunk 1]
```diff
@@ -112,19 +114,26 @@ export default class Controller extends Component {
...
+        if (this.isMouseDownOnController && !isParagraphSelection) {
             this.props.onSelectionClick(controllerNodes);
             selection.removeAllRanges();
             return;
         }
 
-        unwrapNodes(controllerNodes);
         this.props.onHideSidePanel();
 
         if (isSelection && !isSameRange && !selectionContainsInput) {
```
Comment (JonasMS) [inline src/libs/extensionApp/annotationController/src/components/Controller/index.js]: is `isSameRange` still necessary?

Was originally used to maintain controller button displaying in the case of re-selecting the same text. Still applicable?

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js [hunk 2]
```diff
@@ -112,19 +114,26 @@ export default class Controller extends Component {
...
             this.props.onTextSelect(range);
+
+            if (selContainsControllerNodes) {
```
Comment (JonasMS) [inline src/libs/extensionApp/annotationController/src/components/Controller/index.js]: add comment explaining the purpose of this if-statement

/* handles cases where selection is being extended by keys */

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js [hunk 3]
```diff
@@ -147,6 +156,15 @@ export default class Controller extends Component {
...
+    handleMouseDown(e) {
+        const controllerNodes = Array.from(document.querySelectorAll(CONTROLLER_NODE_NAME));
+        this.isMouseDownOnController = this.isTargetNode(e.target, controllerNodes, CONTROLLER_NODE_NAME);
+
+        if (!this.isMouseDownOnController) {
+            unwrapNodes(controllerNodes);
+        }
+    }
+
     // TODO: handleKeyDownEvents
```
Comment (JonasMS) [inline src/libs/extensionApp/annotationController/src/components/Controller/index.js]: remove comments

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js [hunk 4]
```diff
@@ -156,41 +174,52 @@ export default class Controller extends Component {
             return;
         }
 
-        this.setState({displayController: false});
+        // e.preventDefault();
```
Comment (JonasMS) [inline src/libs/extensionApp/annotationController/src/components/Controller/index.js]: remove commented-out code

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js [hunk 5]
```diff
@@ -156,41 +174,52 @@ export default class Controller extends Component {
...
         switch (e.key) {
         case 'Meta':
         case 'Control':
             // TODO display `Note` btn
-            break;
+            return;
+
         case 'Escape':
             if (this.props.isSidePanelDisplayed) {
                 // TODO use constant
```
Comment (JonasMS) [inline src/libs/extensionApp/annotationController/src/components/Controller/index.js]: remove comment

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js [hunk 6]
```diff
@@ -156,41 +174,52 @@ export default class Controller extends Component {
             return;
         }
 
-        this.setState({displayController: false});
+        // e.preventDefault();
 
         switch (e.key) {
         case 'Meta':
         case 'Control':
             // TODO display `Note` btn
```
Comment (JonasMS) [inline src/libs/extensionApp/annotationController/src/components/Controller/index.js]: remove comment

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js [hunk 7]
```diff
@@ -156,41 +174,52 @@ export default class Controller extends Component {
...
-
-        e.preventDefault();
     }
 
     handleKeyUp(e) {
         if (e.preventDefaulted) {
             return;
         }
 
+        // e.preventDefault();
```
Comment (JonasMS) [inline src/libs/extensionApp/annotationController/src/components/Controller/index.js]: remove comment

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js (hunk 1 above)
Comment (JonasMS) [reply src/libs/extensionApp/annotationController/src/components/Controller/index.js]: Leaving it for now - not worth risking accidentally changing behavior.

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js (hunk 2 above)
Comment (JonasMS) [reply src/libs/extensionApp/annotationController/src/components/Controller/index.js]: 👍

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js (hunk 3 above)
Comment (JonasMS) [reply src/libs/extensionApp/annotationController/src/components/Controller/index.js]: 👍

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js (hunk 4 above)
Comment (JonasMS) [reply src/libs/extensionApp/annotationController/src/components/Controller/index.js]: 👍

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js (hunk 5 above)
Comment (JonasMS) [reply src/libs/extensionApp/annotationController/src/components/Controller/index.js]: 👍

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js (hunk 6 above)
Comment (JonasMS) [reply src/libs/extensionApp/annotationController/src/components/Controller/index.js]: 👍

File: src/libs/extensionApp/annotationController/src/components/Controller/index.js (hunk 7 above)
Comment (JonasMS) [reply src/libs/extensionApp/annotationController/src/components/Controller/index.js]: 👍
