### PR TITLE
W498: fix custom titles not appearing in tag-artifact view

### LINKED ISSUE #498: Custom Title Not Supplied In Artifact-Tag View

### PR DESCRIPTION
**Pull request by JonasMS**
close #498

### CODE REVIEW

File: src/server/utils/tag/getTagArtifacts.js [hunk 1]
```diff
@@ -20,14 +20,19 @@ const db = require('../../models/index'),
...
                             required: true,
+                            include: [{
+                                model: db.Users,
+                                where: { id: userID },
+                            }],
                         }, {
                             model: db.Users,
-                            required: true,
+                            where: { id: userID },
+                            // required: true,
```
Comment (JonasMS) [inline src/server/utils/tag/getTagArtifacts.js]: remove commented-out code
